name: makelist
on: [push]
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo content
          uses: actions/checkout@v4
  
        - name: setup python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10.6'
  
        - name: install python packages
          run: |
            python -m pip install --upgrade pip
            pip install beautifulsoup4
  
        - name: execute py script
          run: python makelist.py